---
- hosts: localhost
  connection: local
  tasks:
    - debug: var=ansible_all_ipv4_addresses
    - debug: var=ansible_default_ipv4.address

    - name: Get infos on container
      docker_container_info:
        name: swag
      register: result

    - name: Does container exist?
      debug:
        msg: "The container {{ 'exists' if result.exists else 'does not exist' }}"

    - name: Print information about container
      debug:
        var: result.container.NetworkSettings.Networks["internet-monitoring-back-tier"].IPAddress
      when: result.exists    