---
- name: Create Pi-hole folder on Pi.
  ansible.builtin.file:
    path: "{{ config_dir }}/pi-hole"
    state: directory
    mode: 0755
  become: false

- name: Copy Pi-hole docker-compose template to Pi.
  ansible.builtin.template:
    src: templates/pi-hole-docker-compose.yml.j2
    dest: "{{ config_dir }}/pi-hole/docker-compose.yml"
    mode: '0640'
  become: false

# TODO: The first time this playbook is run, the `pi` user may not be added
# to the `docker` group, so this task may fail.
- name: Ensure Pi-hole is running.
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/pi-hole/"
    build: false
  become: false

- name: Copy Pi-hole dnsmasq file  
  ansible.builtin.template:
    src: templates/04-pihole-dns-reverse-proxy.conf.j2
    dest: "{{ config_dir }}/pi-hole/etc-dnsmasq.d/04-pihole-dns-reverse-proxy.conf"
    mode: '0644'
  when: domain_name_enable  
  become: true

- name: Wait until the file pi-hole/letsencrypt/nginx/proxy-confs/pihole.subdomain.conf.sample is present before continuing
  wait_for:
    path: "{{ config_dir }}/pi-hole/letsencrypt/nginx/proxy-confs/pihole.subdomain.conf.sample"
  when: domain_name_enable

- name: Copy Cloudflare API Key
  ansible.builtin.template:
    src: templates/cloudflare.ini.j2
    dest: "{{ config_dir }}/pi-hole/letsencrypt/dns-conf/cloudflare.ini"
    mode: 0600
  when: domain_name_enable
  become: false  

- name: Copy proxy conf pihole
  ansible.builtin.copy:
    src: "{{ config_dir }}/pi-hole/letsencrypt/nginx/proxy-confs/pihole.subdomain.conf.sample"
    dest: "{{ config_dir }}/pi-hole/letsencrypt/nginx/proxy-confs/pihole.subdomain.conf"
    mode: '0644'
  when: domain_name_enable
  become: true

- name: Copy proxy conf grafana
  ansible.builtin.copy:
    src: "{{ config_dir }}/pi-hole/letsencrypt/nginx/proxy-confs/grafana.subdomain.conf.sample"
    dest: "{{ config_dir }}/pi-hole/letsencrypt/nginx/proxy-confs/grafana.subdomain.conf"
    mode: '0644'
  when: domain_name_enable
  become: true

- name: Copy proxy conf prometheus
  ansible.builtin.copy:
    src: "{{ config_dir }}/pi-hole/letsencrypt/nginx/proxy-confs/prometheus.subdomain.conf.sample"
    dest: "{{ config_dir }}/pi-hole/letsencrypt/nginx/proxy-confs/prometheus.subdomain.conf"
    mode: '0644'
  when: domain_name_enable
  become: true
  notify: Restart pi-hole